FROM nvcr.io/nvidia/pytorch:22.04-py3

WORKDIR /code

ENV TZ=America/Edmonton
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# Install essentials
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        git \
        wait-for-it

RUN apt update \
    && apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        wget \
        gnupg-agent \
        software-properties-common \
        libyaml-cpp-dev \
        libyaml-dev

COPY ./requirements-dev.txt .
RUN pip install requirements-dev.txt

CMD [ "/bin/bash" ]